# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml/

name = "Fanout forwarding starter kit for Rust"
description = "Enables Fanout on a service, forwarding to a backend."
authors = ["<devrel@fastly.com>"]
language = "rust"
manifest_version = 3

[scripts]
  build = "cargo build --profile release"
